Fix WithBaseCall and WithThisCall using parameter type instead of name
dansiegel/CodeGenHelpers pull request #5
Opened 2020-12-01 11:06 UTC by zsr2531

I also made the "unsafe" overloads more flexible, now you can pass constants like `123` or `"hello world"` to base/this.

2020-12-01 11:06 UTC, zsr2531 commented
Closes #4

2020-12-02 21:10 UTC, zsr2531 commented
Ready to merge, if you have no issues/suggestions. :rocket: @dansiegel

2020-12-02 21:45 UTC, dansiegel requested changes

2020-12-02 21:45 UTC, dansiegel commented on src/CodeGenHelpers/ConstructorBuilder.cs
> +        public ConstructorBuilder WithBaseCall(params string[] parameters)
I'd rather that you introduce an override than change the signature outright. You're also outright breaking expected behavior here where the base parameters should be checking for and being added to the parameters in the main constructor... so you might have:

```cs
// expected
public class Foo : Bar
{
    public Foo(string someValue, Baz baz) : base(baz)
    {
    }
}

// builder
constructorBuilder
    .AddParameter("string", "someValue")
    .WithBaseCall(new Dictionary<string, string> { { "Baz", "baz" } });
```

2020-12-03 16:08 UTC, dansiegel commented
I'm going to close this PR... there are some other enhancements I need to make around providing default values for parameters. I'll address this issue as part of that PR.

2020-12-03 16:08 UTC, closed without merging